

FROM bitnami/kafka:2.2.0

WORKDIR /opt/bitnami/kafka

#RUN echo `whoami`
#RUN chmod 777 /etc

#ADD server.properties ./config
#ADD sources.list ./

#RUN alias ll='ls -l' \
#    && mv /etc/apt/sources.list /etc/apt/sources.list.bak \
#    && cp sources.list /etc/apt/sources.list \
#    && DEBIAN_FRONTEND=noninteractive apt-get update


CMD ["sh", "-c", "while true; do sleep 1; done"]
